//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishClass.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_EnglishClassEntities : DbContext
    {
        public db_EnglishClassEntities()
            : base("name=db_EnglishClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Library> tb_Library { get; set; }
        public virtual DbSet<tb_Message> tb_Message { get; set; }
        public virtual DbSet<tb_Plant> tb_Plant { get; set; }
        public virtual DbSet<tb_RecordVideo> tb_RecordVideo { get; set; }
        public virtual DbSet<tb_Result> tb_Result { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<tb_Video> tb_Video { get; set; }
    }
}
