//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Plant
    {
        public int PID { get; set; }
        public int UID { get; set; }
        public int Nums { get; set; }
        public int Days { get; set; }
        public string State { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual tb_User tb_User { get; set; }
    }
}
