//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishClass.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Video()
        {
            this.tb_Library = new HashSet<tb_Library>();
            this.tb_RecordVideo = new HashSet<tb_RecordVideo>();
        }
        [Display(Name = "视频标题")]
        public int VID { get; set; }
        public Nullable<int> UID { get; set; }
        [Display(Name ="视频标题")]
        public string VName { get; set; }
        [Display(Name = "视频地址")]
        public string VAddress { get; set; }
        [Display(Name = "创建时间")]
        public Nullable<System.DateTime> CreateTime { get; set; }
        [Display(Name = "简介")]
        [DataType(DataType.MultilineText)]

        [StringLength(300, ErrorMessage = "录入的字符数超过了300")]
        public string Remake { get; set; }
        [Display(Name = "封面图片")]
        public string Vimage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Library> tb_Library { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RecordVideo> tb_RecordVideo { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
