//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Video()
        {
            this.tb_Library = new HashSet<tb_Library>();
            this.tb_RecordVideo = new HashSet<tb_RecordVideo>();
        }
    
        public int VID { get; set; }
        public int UID { get; set; }
        public string VName { get; set; }
        public string VAddress { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remake { get; set; }
        public string Vimage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Library> tb_Library { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RecordVideo> tb_RecordVideo { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
